# Generated by Django 3.2.9 on 2022-11-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='bio',
            field=models.TextField(default='***No abouts***', verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='bio',
            field=models.TextField(default='***No abouts***', verbose_name='bio'),
        ),
    ]
